//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLimited.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Offering_Tbl
    {
        public int ID { get; set; }
        public string Day { get; set; }
        public System.DateTime Time { get; set; }
        public string Location { get; set; }
        public string Sec_tion { get; set; }
        public int Student_ID { get; set; }
        public int Lab_ID { get; set; }
        public int Course_ID { get; set; }
        public int Semester_ID { get; set; }
    
        public virtual Course_Tbl Course_Tbl { get; set; }
        public virtual Lab_Tbl Lab_Tbl { get; set; }
        public virtual Semester_Tbl_ Semester_Tbl_ { get; set; }
        public virtual Student_Tbl Student_Tbl { get; set; }
    }
}
