//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLimited.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam_Tbl()
        {
            this.Result_Tbl = new HashSet<Result_Tbl>();
        }
    
        public int ID { get; set; }
        public string Exam { get; set; }
        public string Exam_Date { get; set; }
        public int Faculty_ID { get; set; }
        public int Student_ID { get; set; }
    
        public virtual Faculty_Tbl Faculty_Tbl { get; set; }
        public virtual Student_Tbl Student_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result_Tbl> Result_Tbl { get; set; }
    }
}
