//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLimited.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty_Tbl()
        {
            this.Exam_Tbl = new HashSet<Exam_Tbl>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Course_ID { get; set; }
    
        public virtual Course_Tbl Course_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Tbl> Exam_Tbl { get; set; }
    }
}
