//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLimited.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester_Tbl_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester_Tbl_()
        {
            this.Course_Offering_Tbl = new HashSet<Course_Offering_Tbl>();
        }
    
        public int ID { get; set; }
        public string Semester { get; set; }
        public int Semester_number { get; set; }
        public string Desrcip { get; set; }
        public int C_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Offering_Tbl> Course_Offering_Tbl { get; set; }
    }
}
